apiVersion: apps/v1
kind: Deployment
metadata:
  name: cambiarestadoprocedimientos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cambiarestadoprocedimientos
  template:
    metadata:
      labels:
        app: cambiarestadoprocedimientos
    spec:
      containers:
        - name: cambiarestadoprocedimientos
          image: sistemasdba/cambiarestadoprocedimientos:primero
          ports:
            - containerPort: 3000
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "3000"
